### ISSUE TITLE
When build this app,show me the errors!

### ISSUE THREAD

**Issue by wsdjeg** [flschweiger/SwipeStack#1]
![2016-01-30 12 28 53](https://cloud.githubusercontent.com/assets/13142418/12693705/316a7f0c-c74d-11e5-8828-b911bee77301.png)
but I have installed build-tools 23.0.2

**Comment by flschweiger** [comment]
It looks like that you are using a 64-bit version of Ubuntu and some 32-bit packages are missing on your system.

Just install the missing packages on your system and you should be good to go :wink:

**Comment by wsdjeg** [comment]
Oh my God，that means my os is 64-bit,but I am using 32-bit android-sdk,I will confirm it!
