### ISSUE TITLE
Adapter is not reusing views

### ISSUE THREAD

**Issue by tristangrichard** [flschweiger/SwipeStack#11]
Every time a card has to be displayed convertView is null and has to be inflated. getViewTypeCount and getItemViewType are never called

**Comment by andreas-** [comment]
+1

**Comment by flschweiger** [comment]
Currently the views do not get recycled because I don't think it would be a great performance / memory improvement.

**Comment by tristangrichard** [comment]
It is a huge issue! It results often in OOM Exceptions.

**Comment by Gi-lo** [comment]
@trramsiq Why should **not** using view recycling lead to OOM exceptions? At the beginning it will even lead to more memory usage...

**Comment by crearo** [comment]
As @Gi-lo mentioned, it will not result in OOM, though not recycling does lead to bad performance.
The point to note here is, recycling views will lead to better performance in views like listview/gridview where you can scroll your views.

Swipestack however, is a one way flowing list. You cant go back to the previous view once it has been swiped off. Thats why recyling views wont matter. This is why I feel @flschweiger says it wont lead to better performance. Do correct me if wrong, but I hope this clears it up!
