### ISSUE TITLE
Project unavailable

### ISSUE THREAD

**Issue by amineMpdam** [flschweiger/SwipeStack#2]
for some reason the gradle dependency works fine but when running the sample code the app crashes over a class not found exception

**Comment by flschweiger** [comment]
Could you post your logcat output?

**Comment by amineMpdam** [comment]
I'do that as soon as i get home bro
Great work by the way!!

**Comment by amineMpdam** [comment]
Sorry it took me a while to respond but i have been trying to reproduce the error nothing so far!!
Weird no ?
I'm closing the issue for the time being and hopefully the exception won't come up again.
