### ISSUE TITLE
Nativescript implementation

### ISSUE THREAD

**Issue by mikeres0** [flschweiger/SwipeStack#3]
This isn't so much of an issue, but a enhancement suggestion. 

Do you know if SwipeStack has ever been used in a Nativescript application? I think it would benefit a lot of users if a 'port' was created that was compatible with Nativescript.

**Comment by flschweiger** [comment]
Thanks for the suggestion! Unfortunately I do not have any plans for creating a Nativescript compatible version in the near future.
