### ISSUE TITLE
notifyDataSetChange doesn't refresh UI

### ISSUE THREAD

**Issue by lzhAndroid** [flschweiger/SwipeStack#5]
notifyDataSetChange doesn't refresh UI

**Comment by flschweiger** [comment]
Have you looked into the sample application? E.g. `notifyDataSetChanged()` is used when an object is added to the stack by pressing the FAB. It should work as expected.

**Comment by lzhAndroid** [comment]
If the data is not drawn, notify is effective, but if have onLayout, update the top view data, is invalid

**Comment by lzhAndroid** [comment]
my English is not good, reply late,i'm sorry

**Comment by sagargoqii** [comment]
try this method

`mSwipeStack.resetStack()`
